[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft = "<UPDATE HERE>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jimii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"